### ISSUE TITLE
RNN Implementation

### ISSUE THREAD

**Issue by razor1179** [vrenkens/tfkaldi#7]
For training RNNs with CTC the targets and number of frames for every utterance does not need to be aligned. Therefore when training with batches I generated a tensor for training of size `[batch_size, max_frame_size, num_features]`, but as multiple training samples do not have the same `frame_size`, so I padded them with zeros at the end to match the training sample which has the the `max_frame_size` for that particular batch. The `train_seq_len` however has the actual `frame_size` of each input sample in a one dimensional vector `[batch_size]`. With respect to the labels, they are present in a sparse tensor of shape `[batch_size, max_utterance_size]`, where the label vectors which are smaller than `max_utterance_size` are padded with zeros to match it. On doing this I get a very high CTC loss (~5000), I would like to know whether my method for creating the batch data is correct for RNN training. Please let me know

**Comment by vrenkens** [comment]
tfkaldi is not really made for CTC training, I can refer you to my other repository (https://github.com/vrenkens/nabu). Here I implemented several end-to-end architectures. Among others a RNN-CTC architecture.

I think there is no problem with the way you create your batches. I think a very high ctc loss is normal because the loss is not averaged over the batch elements, but summed.

**Comment by razor1179** [comment]
Thank you @vrenkens, the NABU implementation does help. Also have you tried implementing the EESEN framework (https://github.com/srvk/eesen) which has got successful results using CTC for RNN training?

**Comment by vrenkens** [comment]
I have not but I will look into it
